services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888
    ports:
      - 2181:2181

  kafka-1:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_BROKER_ID: 1
      AUTO_CREATE_TOPICS: true
    volumes:
      - ./plugin/debezium-debezium-connector-mysql-2.4.2:/usr/share/java/debezium-debezium-connector-mysql-2.4.2
    ports:
      - 8083:8083
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper-1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=pseudo_test
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:19092
    ports:
      - 8000:8080
    depends_on:
      - kafka-1

  debezium:
    image: debezium/debezium-ui:latest
    platform: linux/amd64
    container_name: debezium
    environment:
      - KAFKA_CONNECT_URIS=http://kafka-1:8083
    ports:
      - 8001:8080
    depends_on:
      - kafka-1

  database:
    image: mysql:8.2.0
    # platform: linux/amd64
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pseudo
      - MYSQL_USER=pseudo
      - MYSQL_PASSWORD=pseudo
      - MYSQL_DATABASE=pseudo
    volumes:
      - ./database/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
